version: "3.2"
services:
  gitkit:
    build: .
    ports:
      - "7080:80"
    volumes:
      - ".:/app"
      - "/home/git:/var/lib/gitkit"
#  gitssh:
#    build: ./docker/gitssh
#    ports:
#      - "7022:22"
#    volumes:
#      - ".:/app"
#      - "/home/git:/home/git"
