version: "3.2"
services:
  gitkit:
    build: ./docker/gitkit
    ports:
      - "7080:80"
    volumes:
      - ".:/app"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "/home/git:/home/git"
  gitssh:
    build: ./docker/gitssh
    ports:
      - "7022:22"
    volumes:
      - ".:/app"
      - "/home/git:/home/git"
