version: "3.2"
services:
  gitkit:
    build:
      context: "."
      dockerfile: "./build/alpine/Dockerfile"
    ports:
      - "7080:80"
      - "7022:22"
    volumes:
      - "./app:/app"
      - "/var/lib/gitkit/repositories:/var/lib/gitkit/repositories"
      - "/var/lib/gitkit/server_keys:/var/lib/gitkit/server_keys"
      - "/var/lib/gitkit/authorized_keys:/var/lib/gitkit/authorized_keys"
    tty: true
