version: "3.2"
services:
  gitkit:
    build:
      context: .
      dockerfile: ./bin/alpine/gitkit/Dockerfile
    ports:
      - "7080:80"
    volumes:
      - "./app:/app"
      - "/home/git:/var/lib/gitkit/repositories"
      - "/home/git/.ssh/authorized_keys:/var/lib/gitkit/authorized_keys"
  gitssh:
    build:
      context: .
      dockerfile: ./bin/alpine/gitssh/Dockerfile
    ports:
      - "7022:22"
    volumes:
      - "/home/git:/home/git"
