#!/usr/bin/env ash

echo "Mapping user from host machine"

HOST_UID=$(stat -c "%u" ${APPLICATION_DATA})
HOST_GID=$(stat -c "%g" ${APPLICATION_DATA})

echo "Using ${HOST_UID}:${HOST_GID}"

usermod -u ${HOST_UID} ${WWW_USER}
groupmod -g ${HOST_GID} ${WWW_GROUP}

chown -R ${HOST_UID}:${HOST_GID} ${APPLICATION_DATA}

exec "$@"
