#!/usr/bin/env bash

REPOSITORIES_ROOT=/home/git

echo "Mapping user from host machine"

HOST_UID=$(stat -c "%u" ${REPOSITORIES_ROOT})
HOST_GID=$(stat -c "%g" ${REPOSITORIES_ROOT})

echo "Using ${HOST_UID}:${HOST_GID}"

# Update UID of `www-data` user (used by php-fpm)
usermod -u ${HOST_UID} www-data
# Update GID of `www-data` group (used by php-fpm)
groupmod -g ${HOST_GID} www-data

chown -R ${HOST_UID}:${HOST_GID} ${REPOSITORIES_ROOT}

exec "$@"
